// Shared guide content: single source of truth for the Guide page AND the
// in-context Help tooltips shown next to fields across the tabs.
import { FULL_METRICS } from "./guideMetrics";

export const GUIDE = [
  { key: "summary", tab: "Summary", group: "Overview",
    purpose: "The one-screen verdict on the account — who it is, how much flows through, and an overall grade.",
    fields: [
      { name: "Identity strip (holder · bank · account · type · period · txns)",
        what: "Who the statement belongs to and what was analysed.",
        how: "Name, bank, account number, account type and period are read from the statement's header pages by the parser. The account number is masked on screen to **** + the last 4 digits. The transaction count is the number of ledger rows extracted.",
        ex: "Mr. PALA SRINIVAS · State Bank of India · A/c ****6546 · Savings Account · 06-Feb-2026 → 20-Aug-2026 · 1,376 txns." },
      { name: "Extraction verified badge",
        what: "Proof the ledger was read correctly before you trust any number.",
        how: "Every row must satisfy: previous balance + amount = new balance (the bank's own printed running balance). Green badge = 0 continuity errors; a red badge shows how many rows failed the check.",
        ex: "“Extraction verified · 1,376 txns · 0 continuity errors” — every one of PALA's 1,376 rows reconciles to the paisa." },
      { name: "Character grade (A–E) + score",
        what: "A single letter summarising the account's credit behaviour.",
        how: "Starts at 100, then deducts: obligation-to-inflow above 30% (−15), any lifestyle flag like alcohol/gaming (−15), a cash-in→transfer-out cycle (−20), bounce events (−10 each, up to 3), and 5+ round-tripping parties (−10). A ≥ 90, B ≥ 75, C ≥ 60, D ≥ 45, else E. The reasons for lost points are listed under the score.",
        ex: "Worked example — start 100. Obligations are 35% of inflows (over the 30% line) → −15. One alcohol flag fired → −15. Two bounce events → −20. No cash-cycle, under 5 round-tripping parties → no further loss. 100 − 50 = 50 → grade D. Every deduction that applied is listed under the score, so the number is always traceable." },
      { name: "Monthly income",
        what: "Typical genuine income per month.",
        how: "Classified income ÷ months analysed. Classified income = credits that look like real income — it excludes self-transfers and non-income credits (loan disbursals, reversals, cashback).",
        ex: "PALA: ₹20,33,732 classified income over 6 months → ₹3,38,955 per month." },
      { name: "Classified income",
        what: "The part of the money coming in that we treat as genuine income.",
        how: "Total credits MINUS anything that isn't earnings: transfers from your own accounts, loan disbursements, reversals and cashback. This is the figure the monthly-income number is divided out of — it is NOT the same as gross credits.",
        ex: "₹10,00,000 credits made up of ₹7,00,000 customer payments + ₹2,00,000 a loan paid in + ₹1,00,000 moved from your own second account → classified income = ₹7,00,000." },
      { name: "Last day balance",
        what: "The closing balance on the final day of the statement — usually the reason the statement was pulled.",
        how: "The running balance on the very last transaction, shown with that date beside it. It is the bank's own printed closing figure, so it should tie exactly to the statement footer.",
        ex: "Period ends 14-Aug-2026 → “Last day balance · 14-Aug-2026  ₹650.47”." },
      { name: "Min balance",
        what: "The lowest the account ever went during the period.",
        how: "The smallest running balance across every transaction. Turns red under ₹100 — a borrower who repeatedly touches zero has no cushion for an EMI presentation.",
        ex: "A statement swinging between ₹3 and ₹3,05,718 shows a min balance of ₹3 — high turnover, no buffer." },
      { name: "Days below",
        what: "How many days the account ran under ₹1,000.",
        how: "Counts calendar days whose end-of-day balance is under ₹1,000, out of the total days in the statement. Shown as “9 / 196”. A high ratio is the clearest sign of hand-to-mouth cash flow.",
        ex: "9 / 196 = tight on a handful of days. 120 / 196 would mean the account is empty most of the month." },
      { name: "Top lender",
        what: "The lender receiving the most repayment money.",
        how: "The Loan Analysis rows sorted by total repaid; the top one is shown with its total. Use it to see who has first claim on the borrower's cash.",
        ex: "“L&T Finance · ₹6,750” — the largest of the detected obligations." },
      { name: "Gross credits",
        what: "All money that came in.",
        how: "Sum of every credit, EXCLUDING transfers from the account holder's own accounts (self-transfers) — so moving your own money around doesn't inflate it.",
        ex: "PALA: ₹20,33,732 across 566 credits." },
      { name: "Gross debits",
        what: "All money that went out.",
        how: "Sum of every debit, self-transfers excluded.",
        ex: "PALA: ₹20,08,798 across 810 debits." },
      { name: "Net surplus",
        what: "What was left over after outflows.",
        how: "Gross credits − gross debits. Shown in red when negative (more went out than came in).",
        ex: "PALA: 20,33,732 − 20,08,798 = ₹24,934 surplus. BHUVANESHWARI: −₹1,02,779 (deficit, shown red)." },
      { name: "Obligations",
        what: "Money going to loans and EMIs.",
        how: "Sum of all debits categorised as loan repayment — NACH/ACH mandate debits, EMIs, daily-collection loans.",
        ex: "PALA: ₹9,750 (4 EMI debits — L&T Finance + Bajaj)." },
      { name: "Obligation / inflow %",
        what: "How much of the income is already committed to debt (a FOIR-style ratio).",
        how: "Obligations ÷ gross credits × 100. Above 30% turns amber and costs 15 grade points.",
        ex: "PALA: 9,750 ÷ 20,33,732 = 0.5% (healthy). BHUVANESHWARI: 27.8% (approaching stress)." },
      { name: "“What the account shows” bullets",
        what: "A short written story of the account, generated from the computed stats.",
        how: "The engine turns its findings into sentences — income pattern, obligations, risk events. A bullet starting with a warning symbol is adverse and is shown in red.",
        ex: "“Merchant/QR-led inflows: 249 settlement credits, ~₹1,02,458/month classified income over 6 months.” (BHUVANESHWARI)" },
      { name: "Cautions card",
        what: "Only the risk flags that actually FIRED, up front.",
        how: "Filters the full flag list to fired flags with severity CRITICAL, WARN or RED. Each row shows the flag id, name and hit count, and clicking it jumps to the Flags tab for the transaction-level detail. The card is hidden when nothing fired.",
        ex: "PALA shows one caution: “F03 Round-tripping parties · 57 hit(s)”." },
      { name: "Income type",
        what: "A quick label for where the money comes from.",
        how: "If more than 20 credits are QR/settlement credits → “Merchant / QR settlements”. Else if salary credits were detected → “Salaried”. Otherwise → “Mixed / transfers”.",
        ex: "BHUVANESHWARI (249 settlement credits) → “Merchant / QR settlements”. PALA → “Mixed / transfers”." },
      { name: "Active lenders",
        what: "How many different lenders are being repaid in this period.",
        how: "Counts the distinct lenders detected in Loan Analysis — each one has at least one repayment inside the statement period. Several at once (lender stacking) is a stress signal.",
        ex: "Two EMI streams — L&T Finance and Bajaj Finance — show as 2 active lenders." },
      { name: "Dominant payee",
        what: "The counterparty the account deals with most.",
        how: "The #1 party from the Parties ledger — ranked by combined money in + out with that party.",
        ex: "PALA's dominant payee is JAKKULA — ₹2,81,511 received across 100 transactions." },
      { name: "Behaviour & risk rows (lifestyle · F02 · F03 · min balance · days below ₹1,000)",
        what: "One-line health checks pulled from the risk tabs.",
        how: "Lifestyle = fired lifestyle flags (green “None” if clean). F02/F03 show instance counts from the Flags tab. Min balance = lowest running balance seen (amber under ₹100). Days below ₹1,000 = days out of the total whose closing balance was under ₹1,000.",
        ex: "PALA: lifestyle None · F02 None · F03 57 parties · min balance ₹3 · 9 / 196 days below ₹1,000." },
    ] },

  { key: "character", tab: "Character", group: "Overview",
    purpose: "Every behavioural signal we can read from the statement — good, bad, and neutral — so nothing is hidden from the reviewer.",
    fields: [
      { name: "Severity colours",
        what: "RED = adverse, AMBER = watch, GREEN = positive, INFO = neutral / for context.",
        how: "Each signal is coloured by its own threshold rule (listed per group below). Positive and neutral signals are deliberately shown too — the reviewer sees the full menu, not just the risks.",
        ex: "PALA: “Alcohol — None detected” shows as INFO (grey), not hidden." },
      { name: "Per-signal stats (count · amount · monthly · % of inflows · % of debits)",
        what: "The same five numbers behind every signal card.",
        how: "count = matching transactions; amount = their total; monthly = amount ÷ months; % of inflows = amount ÷ gross credits; % of debits = amount ÷ gross debits. These feed the severity thresholds.",
        ex: "A signal with 12 txns totalling ₹6,820 over 6 months reads: monthly ₹1,137 · 0.8% of inflows." },
      { name: "Lifestyle & vice (Alcohol · Gambling/Betting · Lottery)",
        what: "Vice spend that lowers the character grade.",
        how: "Merchant/keyword match on the narration (e.g. TASMAC → Alcohol; DREAM11, RUMMY → Gambling). Alcohol turns RED at ≥ 4 txns/month or ≥ 2% of inflows; gambling at ≥ 3/month or ≥ 1%. Below that, any hits show AMBER.",
        ex: "3 alcohol txns of ₹500/month on ₹1L inflows = 1.5% and 3/month → AMBER. 25 txns of ₹40,000 (2.5% of inflows) → RED." },
      { name: "Discretionary lifestyle (Shopping · OTT · Food delivery · Travel)",
        what: "How money is spent — comfort and consumption patterns.",
        how: "Keyword dictionaries per category (AMAZON/FLIPKART → Shopping; NETFLIX/HOTSTAR → OTT; SWIGGY/ZOMATO → Food). Shown as count + amount + % of debits. Informational — not scored.",
        ex: "“Shopping (Amazon/Flipkart…): 14 txns · ₹22,300 · 1.1% of all debits.”" },
      { name: "Borrowing behaviour (active lenders · stacking · daily-collection)",
        what: "Leverage, lender stacking and repayment stress.",
        how: "Counts distinct lenders from loan narrations. Several lenders at once (stacking) or a daily-collection repayment pattern raises severity — both are signs of borrowing under pressure.",
        ex: "BHUVANESHWARI: 4 active lenders (top: Capital India ₹72,546) — flagged for review." },
      { name: "Financial discipline (SIP / mutual funds · insurance · savings)",
        what: "Positive signals that RAISE the reviewer's confidence.",
        how: "Keyword match on investment and insurance narrations (SIP, MUTUAL FUND, LIC…). Any presence shows GREEN.",
        ex: "PALA: one insurance premium of ₹1,000 → GREEN dot on “Insurance premiums”." },
      { name: "Income quality",
        what: "How steady and traceable the income is.",
        how: "Looks at regularity of salary/settlement credits, concentration on a single payer, and how much income arrives as cash versus bank rails.",
        ex: "249 regular QR-settlement credits → steady merchant income; income arriving as irregular cash deposits would score worse." },
      { name: "Balance hygiene",
        what: "The cash cushion — is the account living hand-to-mouth?",
        how: "From daily closing balances: minimum balance, days below ₹1,000, days below ₹100, days at/below zero.",
        ex: "PALA: min ₹3, 9 of 196 days below ₹1,000 — thin on a few days but mostly healthy." },
      { name: "Risk & manipulation",
        what: "Fraud-adjacent behaviour, as character context.",
        how: "The same detectors as the Flags tab — round-tripping, cash-in→out cycles, turnover-inflation patterns — summarised per signal.",
        ex: "PALA: “Round-tripping parties: 57” appears here AND as flag F03." },
    ] },

  { key: "analysis", tab: "Analysis", group: "Overview",
    purpose: "The classic month-by-month ledger summary (Perfios-style): one row per metric, one column per month, plus a total.",
    fields: [
      { name: "Gross Credits / Debits (count & amount)",
        what: "Total money in and out each month.",
        how: "Per-month sum and count of credits (or debits), excluding self-transfers.",
        ex: "PALA's Gross Credits (Amount) row: Feb ₹3,76,683 · Mar ₹2,51,443 · … · total ₹19,58,182 over the 6 complete months." },
      { name: "Self_Sister Credits (Amount)",
        what: "Money received from the account holder's own / related accounts.",
        how: "Credits where the counterparty name matches the account holder (prefix match after cleaning, so truncated names like “KONDAPA R” still match) — or the narration carries the holder's own account number. Carved out so it can't inflate real income.",
        ex: "If Ramesh receives ₹1,00,000 from “RAMESH KUMAR S”, that lands here — not in Business Credits." },
      { name: "Business Credits / Debits",
        what: "Genuine earnings and genuine spending.",
        how: "Business Credits = Gross Credits minus loan disbursements (borrowed money is not income). Business Debits = Gross Debits minus loan repayments.",
        ex: "Month with ₹2,50,000 gross credits including a ₹2,00,000 loan credit → Business Credits ₹50,000." },
      { name: "Cash Deposits / Cash Withdrawals (count & amount)",
        what: "How much physical cash moves through the account.",
        how: "Per-month count and sum of transactions categorised as cash (CDM/CASH DEP, ATM/self withdrawals).",
        ex: "PALA: 0 cash deposits, 3 cash withdrawals totalling ₹40,000." },
      { name: "Loan Transactions / Loan Disbursed (Amount)",
        what: "Loan repayments out, and loan money received in.",
        how: "Loan Transactions = sum of actual loan-repayment debits that month. Loan Disbursed = loan credits received. (We sum real debits; Perfios imputes recurring EMIs, so its figure can run higher.)",
        ex: "PALA May-2026: ₹2,250 L&T EMI appears in Loan Transactions." },
      { name: "Salary Credits (count & amount)",
        what: "Employer salary income detected.",
        how: "Credits categorised as Salary by narration keywords (SALARY, SAL, employer names), counted and summed per month.",
        ex: "A ₹45,000 credit narrated “NEFT-ACME PVT LTD-SALARY JUL” counts here." },
      { name: "Bounce rows (Inward NonTechnical · Outward/Inward Cheque Bounces)",
        what: "Failed payments — a direct repayment-stress signal.",
        how: "Transactions categorised as bounce/return charges (ECS/ACH return, cheque return), counted and summed. Each bounce costs 10 grade points (up to 3).",
        ex: "An “ACH RTN CHG” ₹590 debit lands in Inward NonTechnical Bounces." },
      { name: "Cheque Issues / Deposits (count & amount)",
        what: "Cheque usage in and out.",
        how: "Debits with a cheque number = issues; cheque-narrated credits = deposits.",
        ex: "A ₹50,000 debit with Chq No. 956871 counts as one Cheque Issue." },
      { name: "The month columns & Total",
        what: "How the grid window is chosen — and why one column may carry an asterisk.",
        how: "Every calendar month the statement touches gets a column, INCLUDING a trailing partial month, which is marked with * (the statement ends mid-month, so that column covers only part of it). Including it means the Total column ties back to the statement's own printed summary instead of quietly under-reporting. Note the rendered XLSX keeps the reference report's convention of stopping at the last complete month, so its Analysis sheet can differ from this tab by that partial month.",
        ex: "A statement running 01-Jan → 14-Aug shows Jan…Jul plus Aug*, and Gross Debits totals 1,228 / ₹6,70,642.98 — exactly the statement's own footer." },
      { name: "Why Gross differs from the statement by a few rows",
        what: "Gross Credits/Debits exclude your own self-transfers; the statement's raw totals include them.",
        how: "The two reconcile exactly: Gross + Self_Sister = the statement total. The Self_Sister Credits row on this same tab shows the carved-out amount, so you can always add it back.",
        ex: "Statement 1,228 debits / ₹6,70,642.98 = Gross 1,215 / ₹6,67,791.98 + 13 self-transfers / ₹2,851.00." },
    ] },

  { key: "fullanalysis", tab: "Analysis (Full)", group: "Overview",
    purpose: "The exhaustive 148-metric set (Digitap-parity): every metric per month plus an Overall column. The complete metric-by-metric reference is below.",
    fields: [
      { name: "Reading this tab",
        what: "One row per metric, one column per month, plus Overall.",
        how: "Unlike the Analysis tab, the Overall column here INCLUDES the trailing partial month (marked like “Aug-2026”), so Overall totals match the Summary's full-statement figures. Use the filter box to find a metric.",
        ex: "PALA's Overall “Total Amount of Credit Transactions” = ₹20,33,732 — exactly the Summary's gross credits." },
      { name: "“Not available” state",
        what: "Why this tab can be empty for old records.",
        how: "The 148-metric block is computed at parse time and kept in memory with the rest of the result. If the result has expired or the server restarted, the whole statement is gone — re-upload the PDF to regenerate it.",
        ex: "Upload the same PDF again and the tab fills in." },
      { name: "Balance-date averages (family)",
        what: "Average balance on specific dates lenders care about (3rd–7th, 10th, EMI dates).",
        how: "The closing balance is carried forward for every calendar day, then averaged over the requested dates — this is how a lender checks liquidity on likely EMI dates.",
        ex: "“Average EOD Balance on 3rd 4th 5th 6th 7th” for PALA's Feb-2026: ₹40.40 — dangerously thin in that month." },
      { name: "Rail grid (family)",
        what: "Count and amount by payment channel — UPI, IMPS, NEFT, RTGS, ATM, Cash, Cheque, NACH — split credit vs debit.",
        how: "Each transaction is tagged with its rail from narration keywords, then counted and summed per month per direction.",
        ex: "PALA: 559 UPI credits totalling ₹14,82,489 and 805 UPI debits totalling ₹19,17,798 — an almost fully UPI account." },
      { name: "Category grid (family)",
        what: "Count and amount across 24 spend/income categories (Bills, Food, Alcohol, Travel, Shopping, Loans, Insurance, Gaming…).",
        how: "Each transaction's category from the classifier is rolled up per month — count rows and amount rows separately.",
        ex: "PALA: 39 Bills & Utilities transactions totalling ₹9,440; 1 Insurance transaction of ₹1,000." },
      { name: "Ratios & flags (family)",
        what: "Derived judgements — Debit/Credit ratio, Average credit size, Surplus, Salary & Loan-disbursal flags.",
        how: "Computed from the month's totals (e.g. Surplus = credits − debits that month; Salary Flag = 1 only if salary credits were found).",
        ex: "PALA Overall Surplus = ₹24,933.68; Salary Flag 0 (no employer salary — his income is transfers/UPI)." },
      // ---- full metric-by-metric reference ----
      ...FULL_METRICS.map((m) => ({ name: m.name, what: "Full Analysis metric.", how: m.how, ex: m.ex, compact: true })),
    ] },

  { key: "insights", tab: "Insights", group: "Overview",
    purpose: "The visual read — how the balance moved and where money came from and went.",
    fields: [
      { name: "EOD balance chart",
        what: "Daily closing balance across the whole statement.",
        how: "Takes each day's last balance and carries it forward on days with no transactions. Dips toward zero show tight liquidity.",
        ex: "PALA's chart swings between ₹3 and ₹3,05,718 — spiky merchant-style cashflow." },
      { name: "₹1,000 reference line",
        what: "The dashed line on the balance chart.",
        how: "A fixed ₹1,000 marker — days where the curve sits under this line are the same days counted in “days below ₹1,000” on the Summary.",
        ex: "PALA dips under the line on 9 of 196 days." },
      { name: "“Where money came from” bars",
        what: "Credits grouped by source.",
        how: "Sums CREDITS per category and shows the largest sources as bars.",
        ex: "For a merchant account the top bar is usually “UPI Settlement” or “Transfer from <party>”." },
      { name: "“Where money went” bars",
        what: "Debits grouped by destination.",
        how: "Sums DEBITS per category — transfers, loans, cash, utilities — largest first.",
        ex: "PALA's biggest outflow category: transfers out (₹17,68,922 across 687 txns)." },
    ] },

  { key: "transactions", tab: "Transactions", group: "Transactions",
    purpose: "The full reconstructed ledger, every row, with our enrichments.",
    fields: [
      { name: "Date / Description / Debit / Credit / Balance",
        what: "The ledger exactly as the bank printed it.",
        how: "Parsed from the PDF; the signed amount is split into Debit (red) and Credit (green) columns; Balance is the running balance after the row.",
        ex: "10-Jan-2026 · “TRANSFER FROM 97157001528 /IMPS/P2A/…” · Credit 4,459.00 · Balance 5,007.60." },
      { name: "Category",
        what: "What kind of transaction it is.",
        how: "A rules engine reads the narration: merchant dictionaries (TASMAC → Alcohol, SWIGGY → Food), rail patterns, and party-name extraction (“Transfer to RESHMA R”). Self-transfers become “Transfer to/from Self”.",
        ex: "“UPI/DR/…/DREAM11…” → category Gaming. “NEFT-ACME-SALARY” → Salary." },
      { name: "Rail",
        what: "The payment channel used.",
        how: "Detected from narration tokens, checked in priority order: NACH/ECS → AEPS → UPI-ATM → ATM → UPI → IMPS → RTGS → NEFT → CASH → CARD → CHARGE → INTEREST, else OTHER.",
        ex: "“UPI/CR/544361429036/…” → rail UPI." },
      { name: "Remitter / Beneficiary",
        what: "The other party's name on the transfer.",
        how: "Extracted from the UPI/IMPS narration — each bank prints the name in a different position, and the extractor knows the per-bank ordering.",
        ex: "“UPI/CR/…/A MAHA L/HDFC/9640953318” → remitter “A MAHA L”." },
      { name: "Search & filters + the row cap",
        what: "Narrowing the ledger.",
        how: "Free-text search on the description plus dropdowns for category, rail, and credit/debit. The screen shows at most the first 1,500 matching rows — the downloaded XLSX always has every row.",
        ex: "Filter rail = UPI + Debits → all UPI outflows; the chip shows “805 of 1,376”." },
    ] },

  { key: "upi", tab: "UPI Analysis", group: "Transactions",
    purpose: "An interactive look at small-ticket UPI behaviour.",
    fields: [
      { name: "Threshold ₹X",
        what: "You type an amount; it shows the UPI transactions BELOW it, live.",
        how: "Filters to UPI-rail transactions with |amount| < X and recounts/resums instantly. You can also restrict to credits or debits. Lots of tiny UPI txns usually means retail/QR merchant activity.",
        ex: "PALA with X = ₹200 → hundreds of small QR payments surface; raise X to ₹5,000 and the picture shifts to transfers." },
      { name: "Stat cards (count · amount · Cr/Dr split)",
        what: "The live totals for your threshold.",
        how: "Count of matching rows, their absolute-amount total, and how many are credits vs debits. The table below lists them (first 1,000 rows).",
        ex: "“214 txns below ₹500 · ₹43,120 · 78 Cr / 136 Dr”." },
    ] },

  { key: "highvalue", tab: "High Value", group: "Transactions",
    purpose: "The biggest single inflows and outflows — the transactions that explain the account's story.",
    fields: [
      { name: "High-value credits / debits",
        what: "Every transaction above the high-value threshold.",
        how: "The threshold is ₹10,000 (fixed). Loan transactions and self-transfers are excluded — the table is meant to show genuine large third-party movements within the analysis window.",
        ex: "PALA's top credit: ₹18,000 UPI from “PALA HAR” on 09-Feb-2026 (balance after: ₹19,260)." },
    ] },

  { key: "spend", tab: "Spend Analysis", group: "Money",
    purpose: "Where the money is spent, rolled up by category, month by month.",
    fields: [
      { name: "Category column",
        what: "What kind of spending each row represents.",
        how: "Every debit is assigned a category by the classifier (merchant dictionaries, UPI/IMPS payee names, keywords), then grouped here. The list is fully DYNAMIC — you only see categories that actually occur in this statement, so a simple account may show 3 rows and a busy one 15+. If most spend lands in “Others”, the narration format wasn't recognised for that bank.",
        ex: "A statement with phone bills, an insurance premium and OTT charges shows exactly those 3 rows — not a fixed list." },
      { name: "% debits column",
        what: "How big this category is relative to ALL money going out.",
        how: "Category total ÷ total debits × 100. Use it to see what dominates spending — a category at 40% of debits is where the money actually goes, regardless of how many transactions it has.",
        ex: "Utilities ₹9,440 out of ₹20,08,798 total debits = 0.47% of debits." },
      { name: "Category rows (count · total · monthly split · % of debits)",
        what: "Each spend category with its size and share.",
        how: "Debits are summed per category per month; % of debits = the category's total ÷ all debits. Rows are sorted by total.",
        ex: "PALA: Utilities (Phone) — 39 txns · ₹9,440 total · 0.47% of debits, spread Feb ₹786 → Jul ₹1,200." },
      { name: "Lifestyle pill",
        what: "Marks categories that feed the character grade.",
        how: "Categories in the lifestyle set (alcohol, gaming…) carry a pill so a reviewer can spot vice spend inside the normal spend table. Same detectors as the Character tab.",
        ex: "An “Alcohol · lifestyle” row with ₹6,820 would also appear on the Character and Flags tabs." },
    ] },

  { key: "loans", tab: "Loan Analysis", group: "Money",
    purpose: "Every loan/EMI outflow, with the lender identified and the repayment pattern classified.",
    fields: [
      { name: "Lender name",
        what: "The actual lender behind an EMI/NACH debit.",
        how: "Matches lender keywords and short-codes in the narration against a legal-name lookup (Capital India, ESFB, Bajaj, L&T, Muthoot, UGRO…). Unmatched loan debits stay as generic loan rows.",
        ex: "Narration “MAND DR- LTFPL…” → L&T Finance." },
      { name: "Type",
        what: "What kind of lender it is.",
        how: "The lender lookup also carries a type — Bank, NBFC, Fintech app, Gold loan — shown as a pill.",
        ex: "L&T Finance → NBFC. A gold-loan house like Muthoot → Gold." },
      { name: "Pattern",
        what: "The repayment style — the strongest stress signal here.",
        how: "Classified from mandate tokens and timing: “EMI (Fixed)” = same amount monthly; “NACH mandate” = auto-debit; “Daily collection” = small debits nearly every day (typical of informal/microfinance stress); “One-off / Other” otherwise.",
        ex: "PALA: L&T ₹2,250 × 3 months → EMI (Fixed). Bajaj ₹3,000 once → One-off / Other." },
      { name: "Totals (txn count · total · monthly avg · first/last seen)",
        what: "The size and lifespan of each obligation.",
        how: "Per lender: number of repayment debits, their sum, sum ÷ months active, and the first/last repayment dates.",
        ex: "L&T Finance: 3 txns · ₹6,750 · ₹2,250/month · 29-May → 30-Jul-2026." },
      { name: "Total obligations stat",
        what: "The sum of everything in this table.",
        how: "Adds up each lender row's total. It normally equals the Summary's Obligations figure; the two can differ slightly if a loan debit's lender couldn't be resolved into a row.",
        ex: "PALA: ₹6,750 + ₹3,000 = ₹9,750 — matches the Summary exactly." },
    ] },

  { key: "cashrails", tab: "Cash & Rails", group: "Money",
    purpose: "Two credit questions: how much of this person's money is untraceable cash, and how they actually bank. Heavy cash means income you cannot verify from the statement; a spread across UPI/IMPS/NEFT/RTGS shows a customer comfortable with formal banking rails, while an ATM-and-cash-only profile is harder to underwrite.",
    fields: [
      { name: "Cashflow cards (deposits · withdrawals · net)",
        what: "Physical cash in and out — the part of the money trail that cannot be verified.",
        how: "Counts and sums cash deposits (CDM/branch) and cash withdrawals (ATM/self). Large cash DEPOSITS are the important read: income arriving as cash cannot be traced to a payer, so it is weaker evidence than the same money arriving by UPI or NEFT. Large cash WITHDRAWALS mostly tell you spending happens off-statement.",
        ex: "PALA: 0 cash deposits · 3 ATM withdrawals totalling ₹40,000 → net cash OUT." },
      { name: "Rails table (per channel, in and out)",
        what: "Every payment channel with count and amount, credit vs debit.",
        how: "Each transaction's rail (from the narration) grouped by direction.",
        ex: "PALA: UPI 559 credits ₹14,82,489 / 805 debits ₹19,17,798 — the account lives on UPI." },
    ] },

  { key: "parties", tab: "Parties", group: "Money",
    purpose: "Everyone the account transacts with, and who money flows both ways with.",
    fields: [
      { name: "Party ledger (txns in/out · amount in/out · net)",
        what: "Per counterparty: what came from them, what went to them, and the balance of the relationship.",
        how: "Transactions whose category is “Transfer to/from <name>” are grouped by the extracted name (self-transfers excluded). Net = in − out.",
        ex: "PALA ↔ MAMIDALA: ₹80,950 in (41 txns) · ₹1,19,030 out (15 txns) · net −₹38,080." },
      { name: "Both-sides flag",
        what: "The same party appears on BOTH the credit and debit side.",
        how: "Flagged when a party has money in AND out — a round-tripping candidate, since money circling back can inflate apparent turnover. These parties also feed flag F03.",
        ex: "MAMIDALA (in ₹80,950, out ₹1,19,030) carries the both-sides mark." },
      { name: "Top-40 cutoff",
        what: "Why the table stops at 40 rows.",
        how: "Parties are ranked by combined volume (in + out) and the ledger keeps the top 40 — the XLSX report carries the full party analysis.",
        ex: "Party #41 by volume won't appear here but is still counted in every total." },
      { name: "Monthly Top-5 Received / Transferred",
        what: "The 5 biggest counterparties in EACH month, shown as bars.",
        how: "Each month is ranked independently, so the five names can be COMPLETELY DIFFERENT from month to month — that is the point: you can see whether the same payer recurs (a steady salary/customer) or whether it changes every month (one-off dealings). Each bar is labelled with the counterparty and its amount, and bar length is scaled within that month only, so bars are comparable down a month but not across months. Selection counts party transfers plus Loan, Salary and Interest, and excludes cash, settlements and retail spend so only real funding relationships appear.",
        ex: "If JAKKULA tops March, June and July, that is a recurring funder; if each month shows five new names, the inflows are one-off." },
      { name: "Why Top-5 can show names when the ledger looks empty",
        what: "The two sections are built differently — this used to cause a confusing mismatch.",
        how: "The counterparty ledger needs a NAME parsed out of the narration; the monthly Top-5 falls back to the raw description when no name was resolved. If your bank's narration format wasn't recognised, the ledger came out empty while Top-5 still showed rows (labelled generically, e.g. “Transfer in”). Payee-name extraction is now format-driven and covers all supported banks, so both sections should populate together — an empty ledger with a populated Top-5 now means the narrations genuinely carry no payee name.",
        ex: "Before: ledger “No data”, Top-5 “Transfer in ₹37,102”. Now: ledger lists 145 counterparties and Top-5 shows their actual names." },
    ] },

  { key: "avgbal", tab: "Avg Bal (3rd/4th)", group: "Balances",
    purpose: "Liquidity cushion at the start of the month, when EMIs and rent usually hit.",
    fields: [
      { name: "Close on 3rd · Close on 4th · Average",
        what: "The balance sitting in the account on the 3rd and 4th of each month.",
        how: "Takes the carried-forward closing balance on the 3rd and on the 4th, and averages the two. A thin figure here means an EMI presented early in the month may bounce.",
        ex: "PALA Apr-2026: 3rd ₹46,320 · 4th ₹27,200 → avg ₹36,760 (comfortable). Mar-2026: avg ₹1,521 (tight)." },
    ] },

  { key: "daily", tab: "Daily Balance", group: "Balances",
    purpose: "A day-by-day view of the balance for the whole statement.",
    fields: [
      { name: "Daily open / close / net",
        what: "Opening balance, closing balance and net movement for every day.",
        how: "Derived from the ledger: open = previous day's close; close = the day's last running balance (carried forward across days with no activity); net = close − open.",
        ex: "A day with salary in and rent out might read: open ₹2,140 · close ₹38,900 · net +₹36,760." },
      { name: "Below-₹1,000 marker",
        what: "Days flagged as running on empty.",
        how: "Any day whose close is under ₹1,000 is highlighted — the same days counted on the Summary.",
        ex: "PALA: 9 highlighted days out of 196." },
    ] },

  { key: "flags", tab: "Flags (FCU)", group: "Risk",
    purpose: "Fraud-Control-Unit style risk flags with drill-down to the exact transactions.",
    fields: [
      { name: "Severity scale",
        what: "How serious each flag is.",
        how: "CRITICAL = probe before any sanction (F02). WARN = review recommended (F03). RED = threshold-crossing lifestyle spend. INFO = present but under threshold. Only fired CRITICAL/WARN/RED flags surface on the Summary's Cautions card.",
        ex: "PALA: F03 fired (WARN) → appears in Cautions; F02 not fired → shown here as clean." },
      { name: "F02 · Cash-in → immediate transfer-out cycle",
        what: "Cash deposited and almost immediately pushed out to a fixed party — a possible informal-lender or mule pattern.",
        how: "A cash deposit ≥ ₹20,000 followed within 1 day by an outward transfer of ≥ 80% of it. The flag FIRES when this happens 3 or more times. Each event lists the deposit, the outflow and the recipient.",
        ex: "BHUVANESHWARI: 7 such events → F02 fired (CRITICAL), costing 20 grade points." },
      { name: "F03 · Round-tripping parties",
        what: "Counterparties that money flows to AND from — turnover-inflation risk.",
        how: "Every party appearing on both the credit and debit side, listed with in/out counts and amounts. Fires when at least one exists; 5+ parties also costs 10 grade points.",
        ex: "PALA: 57 two-way parties → fired, and the grade dropped from 100 to 90." },
      { name: "Lifestyle flags + drill-down",
        what: "Vice spend that crossed its threshold, with the exact transactions.",
        how: "Same thresholds as Character (alcohol ≥ 4/month or ≥ 2% of inflows; gaming ≥ 3/month or ≥ 1%). Expanding a flag lists every matching transaction, and each row can jump into the Transactions tab pre-searched.",
        ex: "An alcohol flag expands to show each TASMAC debit with date, amount and balance." },
    ] },

  { key: "qc", tab: "Validation & QC", group: "Risk",
    purpose: "Proof that the extraction is trustworthy before you rely on any number.",
    fields: [
      { name: "Balance continuity breaks",
        what: "Rows where the maths doesn't add up.",
        how: "Counts rows failing previous balance + amount = new balance against the bank's own printed running balance. 0 = a perfect read.",
        ex: "PALA: 0 breaks across 1,376 rows — every figure reconciles." },
      { name: "Categorisation coverage (by txns and by amount)",
        what: "How much of the ledger got a real category rather than “Other”.",
        how: "Two percentages: share of transaction COUNT with a specific category, and share of AMOUNT. Amount coverage is usually lower because big generic transfers are hard to classify further.",
        ex: "PALA: 99.4% of txns categorised · 91.1% of amount." },
      { name: "Missing date ranges",
        what: "Gaps that might mean missing pages.",
        how: "Flags any stretch of MORE THAN 15 DAYS between consecutive transactions — either a dormant account or pages missing from the upload.",
        ex: "A gap from 02-Mar to 28-Mar (26 days) would be listed; verify those pages exist in the PDF." },
      { name: "Unclassified transactions",
        what: "Every row the classifier could NOT label, listed in full so nothing is hidden.",
        how: "These are the rows counted against categorisation coverage. They stay “Others” on purpose: the bank printed either a blank narration or only a reference code, so any label would be a guess — and a wrong label is worse than an honest gap in a credit decision. Each row links through to the ledger so you can judge it yourself.",
        ex: "“(blank in the statement) · ₹47” or “9944360382 4885 · ₹47,500” — a payment reference with no payee name printed anywhere." },
      { name: "Duplicate count",
        what: "Identical rows that may be double-counted.",
        how: "Counts exact duplicates on date + amount + description. A small number is normal (genuinely repeated payments); a large number suggests overlapping statement pages.",
        ex: "PALA: 1 duplicate — two genuine identical UPI payments on the same day." },
      { name: "Password protected",
        what: "Whether the uploaded PDF was locked.",
        how: "“Yes” means the source PDF required a password and was unlocked with the one provided at upload. Purely informational.",
        ex: "BHUVANESHWARI's Union Bank PDF → Yes (password BHUV1205 was used to open it)." },
      { name: "Bank & account echo",
        what: "A restatement of what was detected.",
        how: "The bank and account type as identified by the parser — check these match the physical statement as a sanity check.",
        ex: "“State Bank of India · Savings Account”." },
    ] },

  { key: "statuses", tab: "Statement statuses", group: "General",
    purpose: "What each status on the Statements list means, and what to do about it.",
    fields: [
      { name: "READY",
        what: "Parsed, analysed and viewable.",
        how: "The full pipeline finished: parse → categorise → analyse → render. The View button opens the 16 tabs; XLSX/JSON are downloadable.",
        ex: "“Mr. PALA SRINIVAS · READY · grade A”." },
      { name: "PARSING",
        what: "Still working.",
        how: "Processing runs in the background after upload; the list polls every few seconds until it finishes. Large statements can take a minute or two on the free server.",
        ex: "A 126-page SBI file typically shows PARSING for ~30–90 seconds." },
      { name: "NEEDS PASSWORD",
        what: "The PDF is locked and no (or a wrong) password was given.",
        how: "Click the Password button on the row and enter the PDF's password; parsing then re-runs.",
        ex: "SBI statements are often locked with the account number or DOB." },
      { name: "LOW COVERAGE",
        what: "Parsed successfully, but too many transactions could not be classified — so the analysis is deliberately withheld.",
        how: "After processing, BankIQ checks what share of transactions received a real category. Below the threshold (95% by default) the result is NOT published: every headline number — income, spend, obligations, ratios — is built by summing categorised rows, so publishing with a large unread remainder would understate them without saying so. The row shows the exact coverage achieved and how many rows were unrecognised.",
        ex: "“Only 90% of transactions could be classified (minimum 95%). 5 row(s) were not recognised…” — send that statement format over and it can be supported." },
      { name: "IMAGE SKIPPED",
        what: "A scanned/photographed statement — deliberately not processed.",
        how: "The first pages contain no selectable text (under ~60 characters), so it's a picture of a statement. BankIQ needs a native text PDF; OCR is intentionally not attempted.",
        ex: "“bank statement (1).pdf” — 169 scanned pages → IMAGE SKIPPED with a grey pill, not an error." },
      { name: "EXTRACTION SUSPECT",
        what: "Parsed, but the numbers don't fully reconcile.",
        how: "More than ~1% of rows failed the balance-continuity check. The results open with a warning banner — review before use.",
        ex: "“balance chain broken for 27/1,425 rows” — usable, but verify against the PDF." },
      { name: "UNSUPPORTED / FAILED",
        what: "The layout couldn't be read, or something crashed.",
        how: "UNSUPPORTED = no recognisable transaction table (a bank format we haven't added yet — share the PDF and it can be supported). FAILED shows the actual error text on the row.",
        ex: "A new bank's e-statement layout → UNSUPPORTED until a parser is added for it." },
    ] },

  { key: "privacy", tab: "Privacy & storage", group: "General",
    purpose: "Exactly what happens to a statement after you upload it — and what never happens.",
    fields: [
      { name: "Nothing is written to disk",
        what: "The whole pipeline runs in memory.",
        how: "The uploaded PDF is read into RAM, decrypted in RAM, parsed in RAM, and the results (the analysis and the Excel workbook) are kept only in the server's memory. No file — not the PDF, not a decrypted copy, not the results — is ever saved to storage.",
        ex: "After processing a statement, the server's disk holds exactly what it held before the upload." },
      { name: "Auto-delete (retention timer)",
        what: "Every result has a visible countdown from the moment of upload.",
        how: "A “deleted in …” timer pill sits on each row of the Statements list and in the statement's own header. When under 3 minutes remain, the timer turns RED with a pulse and a confirmation popup appears asking whether to keep it. The trash button still deletes instantly.",
        ex: "Upload at 2:00 pm → the timer counts down from 60m; at 2:57 pm it turns red and the popup shows “About to auto-delete … 2:41”." },
      { name: "Extend (+60 min)",
        what: "Keep a statement in memory longer, deliberately.",
        how: "The “+60m” button on the timer pill (or “Keep for 60 more min” in the popup) resets the countdown to a fresh retention window from that moment. Extending is always an explicit action — nothing is kept longer on its own.",
        ex: "At 5 minutes remaining, press +60m → the timer jumps back to 60:00 and the data stays for another hour." },
      { name: "Gone on restart",
        what: "A server restart or redeploy wipes everything immediately.",
        how: "Because nothing exists outside the process's memory, restarting the server clears every statement — there is nothing left to recover, by design.",
        ex: "After a deploy, the Statements list is empty." },
      { name: "Password-locked PDFs",
        what: "The raw PDF is held in memory only while a password is awaited.",
        how: "When a locked PDF needs a password, its bytes stay in RAM solely so the retry can work. The moment the correct password succeeds (or the record expires), those bytes are dropped.",
        ex: "Enter the right password → the app keeps only the analysis, not the PDF." },
      { name: "No names in server logs",
        what: "Log lines never contain who the statement belongs to.",
        how: "Logs carry only a short random id, sizes, timings and statuses — no upload filename, no account-holder name, no transaction text. So even the hosting platform's log history holds no personal data.",
        ex: "A log line reads “a1b2c3 == DONE -> READY in 9.1s” — nothing identifies the customer." },
      { name: "No caching of results",
        what: "Browsers and proxies are told not to keep copies.",
        how: "Every API response carries Cache-Control: no-store, plus content-sniffing and framing protections — so statement data isn't retained by anything between the server's memory and your screen.",
        ex: "Closing the tab leaves no cached result.json on the machine." },
      { name: "Downloads are yours",
        what: "The XLSX / JSON you download is the one copy that persists.",
        how: "Downloading is a deliberate action — the file is streamed from memory to your machine and it becomes your responsibility to store it safely. The server keeps nothing extra because of a download.",
        ex: "Download the XLSX, and the only lasting copy is the one in your Downloads folder." },
    ] },
];

// flat index for lookups
const FLAT = [];
GUIDE.forEach((t) => t.fields.forEach((f) => FLAT.push({ tab: t.key, ...f })));

// find a guide entry by tab + a fragment of its field name (falls back to any tab)
export function helpFor(tab, q) {
  const ql = q.toLowerCase();
  const hit = FLAT.find((f) => f.tab === tab && f.name.toLowerCase().includes(ql))
    || FLAT.find((f) => f.name.toLowerCase().includes(ql));
  return hit ? { title: hit.name, what: hit.what, how: hit.how, ex: hit.ex } : null;
}

const METRIC_MAP = Object.fromEntries(FULL_METRICS.map((m) => [m.name, m]));
export function metricHelp(label) {
  const m = METRIC_MAP[label];
  return m ? { title: m.name, how: m.how, ex: m.ex } : null;
}
