// Shared guide content: single source of truth for the Guide page AND the
// in-context Help tooltips shown next to fields across the tabs.
import { FULL_METRICS } from "./guideMetrics";

export const GUIDE = [
  { key: "summary", tab: "Summary", group: "Overview",
    purpose: "The one-screen verdict on the account — who it is, how much flows through, and an overall grade.",
    fields: [
      { name: "Identity strip (holder · bank · account · type · period · txns)",
        what: "Who the statement belongs to and what was analysed.",
        how: "Name, bank, account number, account type and period are read from the statement's header pages by the parser. The account number is masked on screen to **** + the last 4 digits. The transaction count is the number of ledger rows extracted.",
        ex: "Mr. PALA SRINIVAS · State Bank of India · A/c ****6546 · Savings Account · 06-Feb-2026 → 20-Aug-2026 · 1,376 txns." },
      { name: "Extraction verified badge",
        what: "Proof the ledger was read correctly before you trust any number.",
        how: "Every row must satisfy: previous balance + amount = new balance (the bank's own printed running balance). Green badge = 0 continuity errors; a red badge shows how many rows failed the check.",
        ex: "“Extraction verified · 1,376 txns · 0 continuity errors” — every one of PALA's 1,376 rows reconciles to the paisa." },
      { name: "Character grade (A–E) + score",
        what: "A single letter summarising the account's credit behaviour.",
        how: "Starts at 100, then deducts: obligation-to-inflow above 30% (−15), any lifestyle flag like alcohol/gaming (−15), a cash-in→transfer-out cycle (−20), bounce events (−10 each, up to 3), and 5+ round-tripping parties (−10). A ≥ 90, B ≥ 75, C ≥ 60, D ≥ 45, else E. The reasons for lost points are listed under the score.",
        ex: "PALA scores 90 → A, losing 10 only for “multiple round-tripping parties”. BHUVANESHWARI scores 70 → C (cash-cycle signal −20, plus round-tripping −10)." },
      { name: "Monthly income",
        what: "Typical genuine income per month.",
        how: "Classified income ÷ months analysed. Classified income = credits that look like real income — it excludes self-transfers and non-income credits (loan disbursals, reversals, cashback).",
        ex: "PALA: ₹20,33,732 classified income over 6 months → ₹3,38,955 per month." },
      { name: "Gross credits",
        what: "All money that came in.",
        how: "Sum of every credit, EXCLUDING transfers from the account holder's own accounts (self-transfers) — so moving your own money around doesn't inflate it.",
        ex: "PALA: ₹20,33,732 across 566 credits." },
      { name: "Gross debits",
        what: "All money that went out.",
        how: "Sum of every debit, self-transfers excluded.",
        ex: "PALA: ₹20,08,798 across 810 debits." },
      { name: "Net surplus",
        what: "What was left over after outflows.",
        how: "Gross credits − gross debits. Shown in red when negative (more went out than came in).",
        ex: "PALA: 20,33,732 − 20,08,798 = ₹24,934 surplus. BHUVANESHWARI: −₹1,02,779 (deficit, shown red)." },
      { name: "Obligations",
        what: "Money going to loans and EMIs.",
        how: "Sum of all debits categorised as loan repayment — NACH/ACH mandate debits, EMIs, daily-collection loans.",
        ex: "PALA: ₹9,750 (4 EMI debits — L&T Finance + Bajaj)." },
      { name: "Obligation / inflow %",
        what: "How much of the income is already committed to debt (a FOIR-style ratio).",
        how: "Obligations ÷ gross credits × 100. Above 30% turns amber and costs 15 grade points.",
        ex: "PALA: 9,750 ÷ 20,33,732 = 0.5% (healthy). BHUVANESHWARI: 27.8% (approaching stress)." },
      { name: "“What the account shows” bullets",
        what: "A short written story of the account, generated from the computed stats.",
        how: "The engine turns its findings into sentences — income pattern, obligations, risk events. A bullet starting with a warning symbol is adverse and is shown in red.",
        ex: "“Merchant/QR-led inflows: 249 settlement credits, ~₹1,02,458/month classified income over 6 months.” (BHUVANESHWARI)" },
      { name: "Cautions card",
        what: "Only the risk flags that actually FIRED, up front.",
        how: "Filters the full flag list to fired flags with severity CRITICAL, WARN or RED. Each row shows the flag id, name and hit count, and clicking it jumps to the Flags tab for the transaction-level detail. The card is hidden when nothing fired.",
        ex: "PALA shows one caution: “F03 Round-tripping parties · 57 hit(s)”." },
      { name: "Income type",
        what: "A quick label for where the money comes from.",
        how: "If more than 20 credits are QR/settlement credits → “Merchant / QR settlements”. Else if salary credits were detected → “Salaried”. Otherwise → “Mixed / transfers”.",
        ex: "BHUVANESHWARI (249 settlement credits) → “Merchant / QR settlements”. PALA → “Mixed / transfers”." },
      { name: "Active lenders & Top lender",
        what: "How many lenders are being repaid, and the biggest one.",
        how: "Active lenders = number of distinct lenders found in the Loan Analysis (each with at least one repayment in the period). Top lender = the one with the highest total repaid.",
        ex: "PALA: 2 active lenders; top = L&T Finance · ₹6,750." },
      { name: "Dominant payee",
        what: "The counterparty the account deals with most.",
        how: "The #1 party from the Parties ledger — ranked by combined money in + out with that party.",
        ex: "PALA's dominant payee is JAKKULA — ₹2,81,511 received across 100 transactions." },
      { name: "Behaviour & risk rows (lifestyle · F02 · F03 · min balance · days below ₹1,000)",
        what: "One-line health checks pulled from the risk tabs.",
        how: "Lifestyle = fired lifestyle flags (green “None” if clean). F02/F03 show instance counts from the Flags tab. Min balance = lowest running balance seen (amber under ₹100). Days below ₹1,000 = days out of the total whose closing balance was under ₹1,000.",
        ex: "PALA: lifestyle None · F02 None · F03 57 parties · min balance ₹3 · 9 / 196 days below ₹1,000." },
    ] },

  { key: "character", tab: "Character", group: "Overview",
    purpose: "Every behavioural signal we can read from the statement — good, bad, and neutral — so nothing is hidden from the reviewer.",
    fields: [
      { name: "Severity colours",
        what: "RED = adverse, AMBER = watch, GREEN = positive, INFO = neutral / for context.",
        how: "Each signal is coloured by its own threshold rule (listed per group below). Positive and neutral signals are deliberately shown too — the reviewer sees the full menu, not just the risks.",
        ex: "PALA: “Alcohol — None detected” shows as INFO (grey), not hidden." },
      { name: "Per-signal stats (count · amount · monthly · % of inflows · % of debits)",
        what: "The same five numbers behind every signal card.",
        how: "count = matching transactions; amount = their total; monthly = amount ÷ months; % of inflows = amount ÷ gross credits; % of debits = amount ÷ gross debits. These feed the severity thresholds.",
        ex: "A signal with 12 txns totalling ₹6,820 over 6 months reads: monthly ₹1,137 · 0.8% of inflows." },
      { name: "Lifestyle & vice (Alcohol · Gambling/Betting · Lottery)",
        what: "Vice spend that lowers the character grade.",
        how: "Merchant/keyword match on the narration (e.g. TASMAC → Alcohol; DREAM11, RUMMY → Gambling). Alcohol turns RED at ≥ 4 txns/month or ≥ 2% of inflows; gambling at ≥ 3/month or ≥ 1%. Below that, any hits show AMBER.",
        ex: "3 alcohol txns of ₹500/month on ₹1L inflows = 1.5% and 3/month → AMBER. 25 txns of ₹40,000 (2.5% of inflows) → RED." },
      { name: "Discretionary lifestyle (Shopping · OTT · Food delivery · Travel)",
        what: "How money is spent — comfort and consumption patterns.",
        how: "Keyword dictionaries per category (AMAZON/FLIPKART → Shopping; NETFLIX/HOTSTAR → OTT; SWIGGY/ZOMATO → Food). Shown as count + amount + % of debits. Informational — not scored.",
        ex: "“Shopping (Amazon/Flipkart…): 14 txns · ₹22,300 · 1.1% of all debits.”" },
      { name: "Borrowing behaviour (active lenders · stacking · daily-collection)",
        what: "Leverage, lender stacking and repayment stress.",
        how: "Counts distinct lenders from loan narrations. Several lenders at once (stacking) or a daily-collection repayment pattern raises severity — both are signs of borrowing under pressure.",
        ex: "BHUVANESHWARI: 4 active lenders (top: Capital India ₹72,546) — flagged for review." },
      { name: "Financial discipline (SIP / mutual funds · insurance · savings)",
        what: "Positive signals that RAISE the reviewer's confidence.",
        how: "Keyword match on investment and insurance narrations (SIP, MUTUAL FUND, LIC…). Any presence shows GREEN.",
        ex: "PALA: one insurance premium of ₹1,000 → GREEN dot on “Insurance premiums”." },
      { name: "Income quality",
        what: "How steady and traceable the income is.",
        how: "Looks at regularity of salary/settlement credits, concentration on a single payer, and how much income arrives as cash versus bank rails.",
        ex: "249 regular QR-settlement credits → steady merchant income; income arriving as irregular cash deposits would score worse." },
      { name: "Balance hygiene",
        what: "The cash cushion — is the account living hand-to-mouth?",
        how: "From daily closing balances: minimum balance, days below ₹1,000, days below ₹100, days at/below zero.",
        ex: "PALA: min ₹3, 9 of 196 days below ₹1,000 — thin on a few days but mostly healthy." },
      { name: "Risk & manipulation",
        what: "Fraud-adjacent behaviour, as character context.",
        how: "The same detectors as the Flags tab — round-tripping, cash-in→out cycles, turnover-inflation patterns — summarised per signal.",
        ex: "PALA: “Round-tripping parties: 57” appears here AND as flag F03." },
    ] },

  { key: "analysis", tab: "Analysis", group: "Overview",
    purpose: "The classic month-by-month ledger summary (Perfios-style): one row per metric, one column per month, plus a total.",
    fields: [
      { name: "Gross Credits / Debits (count & amount)",
        what: "Total money in and out each month.",
        how: "Per-month sum and count of credits (or debits), excluding self-transfers.",
        ex: "PALA's Gross Credits (Amount) row: Feb ₹3,76,683 · Mar ₹2,51,443 · … · total ₹19,58,182 over the 6 complete months." },
      { name: "Self_Sister Credits (Amount)",
        what: "Money received from the account holder's own / related accounts.",
        how: "Credits where the counterparty name matches the account holder (prefix match after cleaning, so truncated names like “KONDAPA R” still match) — or the narration carries the holder's own account number. Carved out so it can't inflate real income.",
        ex: "If Ramesh receives ₹1,00,000 from “RAMESH KUMAR S”, that lands here — not in Business Credits." },
      { name: "Business Credits / Debits",
        what: "Genuine earnings and genuine spending.",
        how: "Business Credits = Gross Credits minus loan disbursements (borrowed money is not income). Business Debits = Gross Debits minus loan repayments.",
        ex: "Month with ₹2,50,000 gross credits including a ₹2,00,000 loan credit → Business Credits ₹50,000." },
      { name: "Cash Deposits / Cash Withdrawals (count & amount)",
        what: "How much physical cash moves through the account.",
        how: "Per-month count and sum of transactions categorised as cash (CDM/CASH DEP, ATM/self withdrawals).",
        ex: "PALA: 0 cash deposits, 3 cash withdrawals totalling ₹2,19,802." },
      { name: "Loan Transactions / Loan Disbursed (Amount)",
        what: "Loan repayments out, and loan money received in.",
        how: "Loan Transactions = sum of actual loan-repayment debits that month. Loan Disbursed = loan credits received. (We sum real debits; Perfios imputes recurring EMIs, so its figure can run higher.)",
        ex: "PALA May-2026: ₹2,250 L&T EMI appears in Loan Transactions." },
      { name: "Salary Credits (count & amount)",
        what: "Employer salary income detected.",
        how: "Credits categorised as Salary by narration keywords (SALARY, SAL, employer names), counted and summed per month.",
        ex: "A ₹45,000 credit narrated “NEFT-ACME PVT LTD-SALARY JUL” counts here." },
      { name: "Bounce rows (Inward NonTechnical · Outward/Inward Cheque Bounces)",
        what: "Failed payments — a direct repayment-stress signal.",
        how: "Transactions categorised as bounce/return charges (ECS/ACH return, cheque return), counted and summed. Each bounce costs 10 grade points (up to 3).",
        ex: "An “ACH RTN CHG” ₹590 debit lands in Inward NonTechnical Bounces." },
      { name: "Cheque Issues / Deposits (count & amount)",
        what: "Cheque usage in and out.",
        how: "Debits with a cheque number = issues; cheque-narrated credits = deposits.",
        ex: "A ₹50,000 debit with Chq No. 956871 counts as one Cheque Issue." },
      { name: "The month columns & Total",
        what: "How the grid window is chosen.",
        how: "Aggregated from the first month to the last COMPLETE month — a trailing partial month is dropped for these summary rows (matching the reference report). Amount rows show 2 decimals; Count rows show none.",
        ex: "PALA's statement runs 06-Feb → 20-Aug, so the grid shows Feb–Jul; the partial August is excluded here (but included in Analysis (Full)'s Overall)." },
    ] },

  { key: "fullanalysis", tab: "Analysis (Full)", group: "Overview",
    purpose: "The exhaustive 148-metric set (Digitap-parity): every metric per month plus an Overall column. The complete metric-by-metric reference is below.",
    fields: [
      { name: "Reading this tab",
        what: "One row per metric, one column per month, plus Overall.",
        how: "Unlike the Analysis tab, the Overall column here INCLUDES the trailing partial month (marked like “Aug-2026”), so Overall totals match the Summary's full-statement figures. Use the filter box to find a metric.",
        ex: "PALA's Overall “Total Amount of Credit Transactions” = ₹20,33,732 — exactly the Summary's gross credits." },
      { name: "“Not available” state",
        what: "Why this tab can be empty for old records.",
        how: "The 148-metric block is computed at parse time and kept in memory with the rest of the result. If the result has expired or the server restarted, the whole statement is gone — re-upload the PDF to regenerate it.",
        ex: "Upload the same PDF again and the tab fills in." },
      { name: "Balance-date averages (family)",
        what: "Average balance on specific dates lenders care about (3rd–7th, 10th, EMI dates).",
        how: "The closing balance is carried forward for every calendar day, then averaged over the requested dates — this is how a lender checks liquidity on likely EMI dates.",
        ex: "“Average EOD Balance on 3rd 4th 5th 6th 7th” for PALA's Feb-2026: ₹40.40 — dangerously thin in that month." },
      { name: "Rail grid (family)",
        what: "Count and amount by payment channel — UPI, IMPS, NEFT, RTGS, ATM, Cash, Cheque, NACH — split credit vs debit.",
        how: "Each transaction is tagged with its rail from narration keywords, then counted and summed per month per direction.",
        ex: "PALA: 559 UPI credits totalling ₹14,82,489 and 805 UPI debits totalling ₹19,17,798 — an almost fully UPI account." },
      { name: "Category grid (family)",
        what: "Count and amount across 24 spend/income categories (Bills, Food, Alcohol, Travel, Shopping, Loans, Insurance, Gaming…).",
        how: "Each transaction's category from the classifier is rolled up per month — count rows and amount rows separately.",
        ex: "PALA: 39 Bills & Utilities transactions totalling ₹9,440; 1 Insurance transaction of ₹1,000." },
      { name: "Ratios & flags (family)",
        what: "Derived judgements — Debit/Credit ratio, Average credit size, Surplus, Salary & Loan-disbursal flags.",
        how: "Computed from the month's totals (e.g. Surplus = credits − debits that month; Salary Flag = 1 only if salary credits were found).",
        ex: "PALA Overall Surplus = ₹24,933.68; Salary Flag 0 (no employer salary — his income is transfers/UPI)." },
      // ---- full metric-by-metric reference ----
      ...FULL_METRICS.map((m) => ({ name: m.name, what: "Full Analysis metric.", how: m.how, ex: m.ex, compact: true })),
    ] },

  { key: "insights", tab: "Insights", group: "Overview",
    purpose: "The visual read — how the balance moved and where money came from and went.",
    fields: [
      { name: "EOD balance chart",
        what: "Daily closing balance across the whole statement.",
        how: "Takes each day's last balance and carries it forward on days with no transactions. Dips toward zero show tight liquidity.",
        ex: "PALA's chart swings between ₹3 and ₹3,05,718 — spiky merchant-style cashflow." },
      { name: "₹1,000 reference line",
        what: "The dashed line on the balance chart.",
        how: "A fixed ₹1,000 marker — days where the curve sits under this line are the same days counted in “days below ₹1,000” on the Summary.",
        ex: "PALA dips under the line on 9 of 196 days." },
      { name: "“Where money came from” bars",
        what: "Credits grouped by source.",
        how: "Sums CREDITS per category and shows the largest sources as bars.",
        ex: "For a merchant account the top bar is usually “UPI Settlement” or “Transfer from <party>”." },
      { name: "“Where money went” bars",
        what: "Debits grouped by destination.",
        how: "Sums DEBITS per category — transfers, loans, cash, utilities — largest first.",
        ex: "PALA's biggest outflow category: transfers out (₹17,68,922 across 687 txns)." },
    ] },

  { key: "transactions", tab: "Transactions", group: "Transactions",
    purpose: "The full reconstructed ledger, every row, with our enrichments.",
    fields: [
      { name: "Date / Description / Debit / Credit / Balance",
        what: "The ledger exactly as the bank printed it.",
        how: "Parsed from the PDF; the signed amount is split into Debit (red) and Credit (green) columns; Balance is the running balance after the row.",
        ex: "10-Jan-2026 · “TRANSFER FROM 97157001528 /IMPS/P2A/…” · Credit 4,459.00 · Balance 5,007.60." },
      { name: "Category",
        what: "What kind of transaction it is.",
        how: "A rules engine reads the narration: merchant dictionaries (TASMAC → Alcohol, SWIGGY → Food), rail patterns, and party-name extraction (“Transfer to RESHMA R”). Self-transfers become “Transfer to/from Self”.",
        ex: "“UPI/DR/…/DREAM11…” → category Gaming. “NEFT-ACME-SALARY” → Salary." },
      { name: "Rail",
        what: "The payment channel used.",
        how: "Detected from narration tokens, checked in priority order: NACH/ECS → AEPS → UPI-ATM → ATM → UPI → IMPS → RTGS → NEFT → CASH → CARD → CHARGE → INTEREST, else OTHER.",
        ex: "“UPI/CR/544361429036/…” → rail UPI." },
      { name: "Remitter / Beneficiary",
        what: "The other party's name on the transfer.",
        how: "Extracted from the UPI/IMPS narration — each bank prints the name in a different position, and the extractor knows the per-bank ordering.",
        ex: "“UPI/CR/…/A MAHA L/HDFC/9640953318” → remitter “A MAHA L”." },
      { name: "Search & filters + the row cap",
        what: "Narrowing the ledger.",
        how: "Free-text search on the description plus dropdowns for category, rail, and credit/debit. The screen shows at most the first 1,500 matching rows — the downloaded XLSX always has every row.",
        ex: "Filter rail = UPI + Debits → all UPI outflows; the chip shows “805 of 1,376”." },
    ] },

  { key: "upi", tab: "UPI Analysis", group: "Transactions",
    purpose: "An interactive look at small-ticket UPI behaviour.",
    fields: [
      { name: "Threshold ₹X",
        what: "You type an amount; it shows the UPI transactions BELOW it, live.",
        how: "Filters to UPI-rail transactions with |amount| < X and recounts/resums instantly. You can also restrict to credits or debits. Lots of tiny UPI txns usually means retail/QR merchant activity.",
        ex: "PALA with X = ₹200 → hundreds of small QR payments surface; raise X to ₹5,000 and the picture shifts to transfers." },
      { name: "Stat cards (count · amount · Cr/Dr split)",
        what: "The live totals for your threshold.",
        how: "Count of matching rows, their absolute-amount total, and how many are credits vs debits. The table below lists them (first 1,000 rows).",
        ex: "“214 txns below ₹500 · ₹43,120 · 78 Cr / 136 Dr”." },
    ] },

  { key: "highvalue", tab: "High Value", group: "Transactions",
    purpose: "The biggest single inflows and outflows — the transactions that explain the account's story.",
    fields: [
      { name: "High-value credits / debits",
        what: "Every transaction above the high-value threshold.",
        how: "The threshold is ₹10,000 (fixed). Loan transactions and self-transfers are excluded — the table is meant to show genuine large third-party movements within the analysis window.",
        ex: "PALA's top credit: ₹18,000 UPI from “PALA HAR” on 09-Feb-2026 (balance after: ₹19,260)." },
    ] },

  { key: "spend", tab: "Spend Analysis", group: "Money",
    purpose: "Where the money is spent, rolled up by category, month by month.",
    fields: [
      { name: "Category rows (count · total · monthly split · % of debits)",
        what: "Each spend category with its size and share.",
        how: "Debits are summed per category per month; % of debits = the category's total ÷ all debits. Rows are sorted by total.",
        ex: "PALA: Utilities (Phone) — 39 txns · ₹9,440 total · 0.47% of debits, spread Feb ₹786 → Jul ₹1,200." },
      { name: "Lifestyle pill",
        what: "Marks categories that feed the character grade.",
        how: "Categories in the lifestyle set (alcohol, gaming…) carry a pill so a reviewer can spot vice spend inside the normal spend table. Same detectors as the Character tab.",
        ex: "An “Alcohol · lifestyle” row with ₹6,820 would also appear on the Character and Flags tabs." },
    ] },

  { key: "loans", tab: "Loan Analysis", group: "Money",
    purpose: "Every loan/EMI outflow, with the lender identified and the repayment pattern classified.",
    fields: [
      { name: "Lender name",
        what: "The actual lender behind an EMI/NACH debit.",
        how: "Matches lender keywords and short-codes in the narration against a legal-name lookup (Capital India, ESFB, Bajaj, L&T, Muthoot, UGRO…). Unmatched loan debits stay as generic loan rows.",
        ex: "Narration “MAND DR- LTFPL…” → L&T Finance." },
      { name: "Type",
        what: "What kind of lender it is.",
        how: "The lender lookup also carries a type — Bank, NBFC, Fintech app, Gold loan — shown as a pill.",
        ex: "L&T Finance → NBFC. A gold-loan house like Muthoot → Gold." },
      { name: "Pattern",
        what: "The repayment style — the strongest stress signal here.",
        how: "Classified from mandate tokens and timing: “EMI (Fixed)” = same amount monthly; “NACH mandate” = auto-debit; “Daily collection” = small debits nearly every day (typical of informal/microfinance stress); “One-off / Other” otherwise.",
        ex: "PALA: L&T ₹2,250 × 3 months → EMI (Fixed). Bajaj ₹3,000 once → One-off / Other." },
      { name: "Totals (txn count · total · monthly avg · first/last seen)",
        what: "The size and lifespan of each obligation.",
        how: "Per lender: number of repayment debits, their sum, sum ÷ months active, and the first/last repayment dates.",
        ex: "L&T Finance: 3 txns · ₹6,750 · ₹2,250/month · 29-May → 30-Jul-2026." },
      { name: "Total obligations stat",
        what: "The sum of everything in this table.",
        how: "Adds up each lender row's total. It normally equals the Summary's Obligations figure; the two can differ slightly if a loan debit's lender couldn't be resolved into a row.",
        ex: "PALA: ₹6,750 + ₹3,000 = ₹9,750 — matches the Summary exactly." },
    ] },

  { key: "cashrails", tab: "Cash & Rails", group: "Money",
    purpose: "How cash-dependent the account is, and which channels move the money.",
    fields: [
      { name: "Cashflow cards (deposits · withdrawals · net)",
        what: "Physical cash in and out.",
        how: "Counts and sums the cash-deposit and cash-withdrawal categories. Heavy cash flow makes income harder to verify — a quality signal, not automatically bad.",
        ex: "PALA: 0 cash deposits · 3 withdrawals totalling ₹2,19,802 → net cash OUT." },
      { name: "Rails table (per channel, in and out)",
        what: "Every payment channel with count and amount, credit vs debit.",
        how: "Each transaction's rail (from the narration) grouped by direction.",
        ex: "PALA: UPI 559 credits ₹14,82,489 / 805 debits ₹19,17,798 — the account lives on UPI." },
    ] },

  { key: "parties", tab: "Parties", group: "Money",
    purpose: "Everyone the account transacts with, and who money flows both ways with.",
    fields: [
      { name: "Party ledger (txns in/out · amount in/out · net)",
        what: "Per counterparty: what came from them, what went to them, and the balance of the relationship.",
        how: "Transactions whose category is “Transfer to/from <name>” are grouped by the extracted name (self-transfers excluded). Net = in − out.",
        ex: "PALA ↔ MAMIDALA: ₹80,950 in (41 txns) · ₹1,19,030 out (15 txns) · net −₹38,080." },
      { name: "Both-sides flag",
        what: "The same party appears on BOTH the credit and debit side.",
        how: "Flagged when a party has money in AND out — a round-tripping candidate, since money circling back can inflate apparent turnover. These parties also feed flag F03.",
        ex: "MAMIDALA (in ₹80,950, out ₹1,19,030) carries the both-sides mark." },
      { name: "Top-40 cutoff",
        what: "Why the table stops at 40 rows.",
        how: "Parties are ranked by combined volume (in + out) and the ledger keeps the top 40 — the XLSX report carries the full party analysis.",
        ex: "Party #41 by volume won't appear here but is still counted in every total." },
      { name: "Monthly Top-5 Received / Transferred",
        what: "The 5 biggest counterparties for each month, as bars.",
        how: "Per month, the top 5 by amount — counting party transfers plus Loan, Salary and Interest categories, and excluding cash, settlements and retail spend (so the list shows real funding relationships, matching the reference report's Top-5 rule).",
        ex: "“Jun-2026 · Received: JAKKULA ₹62,000 · RAMESH ₹31,500 · …” — the month's key funders at a glance." },
    ] },

  { key: "avgbal", tab: "Avg Bal (3rd/4th)", group: "Balances",
    purpose: "Liquidity cushion at the start of the month, when EMIs and rent usually hit.",
    fields: [
      { name: "Close on 3rd · Close on 4th · Average",
        what: "The balance sitting in the account on the 3rd and 4th of each month.",
        how: "Takes the carried-forward closing balance on the 3rd and on the 4th, and averages the two. A thin figure here means an EMI presented early in the month may bounce.",
        ex: "PALA Apr-2026: 3rd ₹46,320 · 4th ₹27,200 → avg ₹36,760 (comfortable). Mar-2026: avg ₹1,521 (tight)." },
    ] },

  { key: "daily", tab: "Daily Balance", group: "Balances",
    purpose: "A day-by-day view of the balance for the whole statement.",
    fields: [
      { name: "Daily open / close / net",
        what: "Opening balance, closing balance and net movement for every day.",
        how: "Derived from the ledger: open = previous day's close; close = the day's last running balance (carried forward across days with no activity); net = close − open.",
        ex: "A day with salary in and rent out might read: open ₹2,140 · close ₹38,900 · net +₹36,760." },
      { name: "Below-₹1,000 marker",
        what: "Days flagged as running on empty.",
        how: "Any day whose close is under ₹1,000 is highlighted — the same days counted on the Summary.",
        ex: "PALA: 9 highlighted days out of 196." },
    ] },

  { key: "flags", tab: "Flags (FCU)", group: "Risk",
    purpose: "Fraud-Control-Unit style risk flags with drill-down to the exact transactions.",
    fields: [
      { name: "Severity scale",
        what: "How serious each flag is.",
        how: "CRITICAL = probe before any sanction (F02). WARN = review recommended (F03). RED = threshold-crossing lifestyle spend. INFO = present but under threshold. Only fired CRITICAL/WARN/RED flags surface on the Summary's Cautions card.",
        ex: "PALA: F03 fired (WARN) → appears in Cautions; F02 not fired → shown here as clean." },
      { name: "F02 · Cash-in → immediate transfer-out cycle",
        what: "Cash deposited and almost immediately pushed out to a fixed party — a possible informal-lender or mule pattern.",
        how: "A cash deposit ≥ ₹20,000 followed within 1 day by an outward transfer of ≥ 80% of it. The flag FIRES when this happens 3 or more times. Each event lists the deposit, the outflow and the recipient.",
        ex: "BHUVANESHWARI: 7 such events → F02 fired (CRITICAL), costing 20 grade points." },
      { name: "F03 · Round-tripping parties",
        what: "Counterparties that money flows to AND from — turnover-inflation risk.",
        how: "Every party appearing on both the credit and debit side, listed with in/out counts and amounts. Fires when at least one exists; 5+ parties also costs 10 grade points.",
        ex: "PALA: 57 two-way parties → fired, and the grade dropped from 100 to 90." },
      { name: "Lifestyle flags + drill-down",
        what: "Vice spend that crossed its threshold, with the exact transactions.",
        how: "Same thresholds as Character (alcohol ≥ 4/month or ≥ 2% of inflows; gaming ≥ 3/month or ≥ 1%). Expanding a flag lists every matching transaction, and each row can jump into the Transactions tab pre-searched.",
        ex: "An alcohol flag expands to show each TASMAC debit with date, amount and balance." },
    ] },

  { key: "qc", tab: "Validation & QC", group: "Risk",
    purpose: "Proof that the extraction is trustworthy before you rely on any number.",
    fields: [
      { name: "Balance continuity breaks",
        what: "Rows where the maths doesn't add up.",
        how: "Counts rows failing previous balance + amount = new balance against the bank's own printed running balance. 0 = a perfect read.",
        ex: "PALA: 0 breaks across 1,376 rows — every figure reconciles." },
      { name: "Categorisation coverage (by txns and by amount)",
        what: "How much of the ledger got a real category rather than “Other”.",
        how: "Two percentages: share of transaction COUNT with a specific category, and share of AMOUNT. Amount coverage is usually lower because big generic transfers are hard to classify further.",
        ex: "PALA: 99.4% of txns categorised · 91.1% of amount." },
      { name: "Missing date ranges",
        what: "Gaps that might mean missing pages.",
        how: "Flags any stretch of MORE THAN 15 DAYS between consecutive transactions — either a dormant account or pages missing from the upload.",
        ex: "A gap from 02-Mar to 28-Mar (26 days) would be listed; verify those pages exist in the PDF." },
      { name: "Duplicate count",
        what: "Identical rows that may be double-counted.",
        how: "Counts exact duplicates on date + amount + description. A small number is normal (genuinely repeated payments); a large number suggests overlapping statement pages.",
        ex: "PALA: 1 duplicate — two genuine identical UPI payments on the same day." },
      { name: "Password protected",
        what: "Whether the uploaded PDF was locked.",
        how: "“Yes” means the source PDF required a password and was unlocked with the one provided at upload. Purely informational.",
        ex: "BHUVANESHWARI's Union Bank PDF → Yes (password BHUV1205 was used to open it)." },
      { name: "Bank & account echo",
        what: "A restatement of what was detected.",
        how: "The bank and account type as identified by the parser — check these match the physical statement as a sanity check.",
        ex: "“State Bank of India · Savings Account”." },
    ] },

  { key: "statuses", tab: "Statement statuses", group: "General",
    purpose: "What each status on the Statements list means, and what to do about it.",
    fields: [
      { name: "READY",
        what: "Parsed, analysed and viewable.",
        how: "The full pipeline finished: parse → categorise → analyse → render. The View button opens the 16 tabs; XLSX/JSON are downloadable.",
        ex: "“Mr. PALA SRINIVAS · READY · grade A”." },
      { name: "PARSING",
        what: "Still working.",
        how: "Processing runs in the background after upload; the list polls every few seconds until it finishes. Large statements can take a minute or two on the free server.",
        ex: "A 126-page SBI file typically shows PARSING for ~30–90 seconds." },
      { name: "NEEDS PASSWORD",
        what: "The PDF is locked and no (or a wrong) password was given.",
        how: "Click the Password button on the row and enter the PDF's password; parsing then re-runs.",
        ex: "SBI statements are often locked with the account number or DOB." },
      { name: "IMAGE SKIPPED",
        what: "A scanned/photographed statement — deliberately not processed.",
        how: "The first pages contain no selectable text (under ~60 characters), so it's a picture of a statement. BankIQ needs a native text PDF; OCR is intentionally not attempted.",
        ex: "“bank statement (1).pdf” — 169 scanned pages → IMAGE SKIPPED with a grey pill, not an error." },
      { name: "EXTRACTION SUSPECT",
        what: "Parsed, but the numbers don't fully reconcile.",
        how: "More than ~1% of rows failed the balance-continuity check. The results open with a warning banner — review before use.",
        ex: "“balance chain broken for 27/1,425 rows” — usable, but verify against the PDF." },
      { name: "UNSUPPORTED / FAILED",
        what: "The layout couldn't be read, or something crashed.",
        how: "UNSUPPORTED = no recognisable transaction table (a bank format we haven't added yet — share the PDF and it can be supported). FAILED shows the actual error text on the row.",
        ex: "A new bank's e-statement layout → UNSUPPORTED until a parser is added for it." },
    ] },

  { key: "privacy", tab: "Privacy & storage", group: "General",
    purpose: "Exactly what happens to a statement after you upload it — and what never happens.",
    fields: [
      { name: "Nothing is written to disk",
        what: "The whole pipeline runs in memory.",
        how: "The uploaded PDF is read into RAM, decrypted in RAM, parsed in RAM, and the results (the analysis and the Excel workbook) are kept only in the server's memory. No file — not the PDF, not a decrypted copy, not the results — is ever saved to storage.",
        ex: "After processing a statement, the server's disk holds exactly what it held before the upload." },
      { name: "Auto-delete (retention timer)",
        what: "Every result has a countdown from the moment of upload.",
        how: "Results are purged from memory automatically after the retention window (shown in the banner, default 60 minutes). Each row on the Statements list shows its remaining time. The trash button deletes instantly.",
        ex: "Upload at 2:00 pm → the result and the PDF are gone from memory by 3:00 pm, viewed or not." },
      { name: "Gone on restart",
        what: "A server restart or redeploy wipes everything immediately.",
        how: "Because nothing exists outside the process's memory, restarting the server clears every statement — there is nothing left to recover, by design.",
        ex: "After a deploy, the Statements list is empty." },
      { name: "Password-locked PDFs",
        what: "The raw PDF is held in memory only while a password is awaited.",
        how: "When a locked PDF needs a password, its bytes stay in RAM solely so the retry can work. The moment the correct password succeeds (or the record expires), those bytes are dropped.",
        ex: "Enter the right password → the app keeps only the analysis, not the PDF." },
      { name: "No names in server logs",
        what: "Log lines never contain who the statement belongs to.",
        how: "Logs carry only a short random id, sizes, timings and statuses — no upload filename, no account-holder name, no transaction text. So even the hosting platform's log history holds no personal data.",
        ex: "A log line reads “a1b2c3 == DONE -> READY in 9.1s” — nothing identifies the customer." },
      { name: "No caching of results",
        what: "Browsers and proxies are told not to keep copies.",
        how: "Every API response carries Cache-Control: no-store, plus content-sniffing and framing protections — so statement data isn't retained by anything between the server's memory and your screen.",
        ex: "Closing the tab leaves no cached result.json on the machine." },
      { name: "Downloads are yours",
        what: "The XLSX / JSON you download is the one copy that persists.",
        how: "Downloading is a deliberate action — the file is streamed from memory to your machine and it becomes your responsibility to store it safely. The server keeps nothing extra because of a download.",
        ex: "Download the XLSX, and the only lasting copy is the one in your Downloads folder." },
    ] },
];

// flat index for lookups
const FLAT = [];
GUIDE.forEach((t) => t.fields.forEach((f) => FLAT.push({ tab: t.key, ...f })));

// find a guide entry by tab + a fragment of its field name (falls back to any tab)
export function helpFor(tab, q) {
  const ql = q.toLowerCase();
  const hit = FLAT.find((f) => f.tab === tab && f.name.toLowerCase().includes(ql))
    || FLAT.find((f) => f.name.toLowerCase().includes(ql));
  return hit ? { title: hit.name, what: hit.what, how: hit.how, ex: hit.ex } : null;
}

const METRIC_MAP = Object.fromEntries(FULL_METRICS.map((m) => [m.name, m]));
export function metricHelp(label) {
  const m = METRIC_MAP[label];
  return m ? { title: m.name, how: m.how, ex: m.ex } : null;
}
